import Head from 'next/head'
import { BsSearch } from 'react-icons/bs'
import { useState } from 'react'
import { api } from '@/services/api'
export default function Home() {

  const [input,setInput] = useState("")

  const [cep,setCep] = useState({})
  
  const handleKeyPress = (e) => {
    // look for the `Enter` keyCode
    if (e.keyCode === 13 || e.which === 13) {
      handleSearch()
    }
  }

  const handleSearch = async  () => {
    if(input === ''){
      alert('Digite um CEP')
      return;
    }

    try{
      const response = await api.get(`${input}/json`)
      setCep(response.data)
      setInput('')
    }
    catch{
      alert('Erro ao buscar')
      setInput('')
    }
  }

  return (
    <div>
      <Head>
        <title>Buscador CEP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className=' h-screen flex flex-col justify-center items-center bg-gradient-to-b from-slate-700 to-black'>
      <h1 className='text-5xl text-center px-4 pt-3 text-white font-bold'>
        Buscador de CEP
      </h1>
      <div className='flex justify-center pt-4 items-center shadow-lg bg-slate-500 px-8 p-4 rounded-lg mt-8'>
        <input onKeyPress={handleKeyPress} className='focus:outline-0 bg-transparent placeholder:text-slate-200 placeholder:text-lg placeholder:font-semibold font-semibold text-lg text-slate-200'  type='text' value={input} onChange={(e) => setInput(e.target.value)} placeholder='Digite seu CEP'></input>
        <button type='submit' onClick={handleSearch} className='pl-2'>
          <BsSearch className=' hover:scale-125 duration-300' size={20} color='white'/>
        </button>
      </div>

      {Object.keys(cep).length > 0 && (
        <div className='flex flex-col justify-center items-center bg-white shadow-lg rounded-md mt-4 p-5 w-2/3 md:w-[450px]'>
        <h2 className='mb-2 text-2xl md:text-4xl font-bold'>CEP: {cep.cep}</h2>
        <span className=' md:text-2xl text-gray-700 text-lg mb-2'> {cep.logradouro}</span>
        <span className=' md:text-2xl text-gray-700 text-lg mb-2'>{cep.bairro}</span>
        <span className=' md:text-2xl text-gray-700 text-lg mb-2'>{cep.localidade}</span>
        <span className=' md:text-2xl text-gray-700 text-lg mb-2'>{cep.uf}</span>
      </div>
      )}
      
      </main>
    </div>
  )
}
